export enum ValidationErrorCode {
  REQUIRED = 'VALIDATION_REQUIRED',
  INVALID_INPUT = 'VALIDATION_INVALID_INPUT',

  EMAIL_REQUIRED = 'VALIDATION_EMAIL_REQUIRED',
  EMAIL_INVALID = 'VALIDATION_EMAIL_INVALID',

  PASSWORD_REQUIRED = 'VALIDATION_PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT = 'VALIDATION_PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG = 'VALIDATION_PASSWORD_TOO_LONG',
  PASSWORD_MISSING_UPPERCASE = 'VALIDATION_PASSWORD_MISSING_UPPERCASE',
  PASSWORD_MISSING_NUMBER = 'VALIDATION_PASSWORD_MISSING_NUMBER',
  PASSWORD_CONFIRMATION_REQUIRED = 'VALIDATION_PASSWORD_CONFIRMATION_REQUIRED',
  PASSWORDS_DO_NOT_MATCH = 'VALIDATION_PASSWORDS_DO_NOT_MATCH',

  NAME_REQUIRED = 'VALIDATION_NAME_REQUIRED',
  NAME_TOO_SHORT = 'VALIDATION_NAME_TOO_SHORT',
  NAME_INVALID_FORMAT = 'VALIDATION_NAME_INVALID_FORMAT',

  UUID_INVALID = 'VALIDATION_UUID_INVALID',
  TOO_SHORT = 'VALIDATION_TOO_SHORT',
  TOO_LONG = 'VALIDATION_TOO_LONG',
  INVALID_ROLE = 'VALIDATION_INVALID_ROLE',
}
